version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: starshop-postgres
    environment:
      POSTGRES_USER: staruser
      POSTGRES_PASSWORD: starpass
      POSTGRES_DB: starshop
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U staruser -d starshop"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped


